---
output: 
  pdf_document:
    includes:
      before_body: Portada.tex
      in_header: 
    toc: true
    toc_depth: 3
  tables: true
include-before:
- '`\newpage{}`{=latex}'
toc-title: Contenido
urlcolor: blue
header-includes:
- \usepackage[nottoc]{tocbibind}
- \renewcommand{\listfigurename}{Lista de figuras}
- \renewcommand{\listtablename}{Lista de tablas}
- \usepackage[utf8]{inputenc}
- \usepackage[spanish]{babel}
- \usepackage{graphicx}
- \usepackage{float}
- \usepackage{lscape}
- \usepackage{amsmath}
---

\newpage

\listoffigures

\listoftables

```{r setup,                     include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	fig.align = "center",
	fig.height = 3,
	fig.pos = "H",
	fig.width = 7,
	message = FALSE,
	warning = FALSE
)
```

\newpage

# Preguntas teóricas
**Resuelva los ejercicios 9.1, 9.4, 9.8 y 9.11 (5a edición). Realice estos con ayuda de su laboratorista y entregue las soluciones escritas a máquina, utilizando LaTeX.**

## Ejercicio 9.1, Romer (5ta Edicion)

\begin{enumerate}
\item[] \textbf{9.1} Consider a firm that produces output using a Cobb Douglas combination of capital
and labor:$Y=K^{\alpha}L^{1- \alpha},0<\alpha<1$. Suppose that the firm’s price is fixed in the short run; thus it takes both the price of its product, $P$ , and the quantity, $Y$, as given. Input markets are competitive; thus the firm takes the wage, $W$, and the rental price of capital, $r_{K}$, as given.
\end{enumerate}

### (a)
\begin{enumerate}
\item[] \textit{What is the firm’s choice of $L$ given $P$ , $Y$, $W$, and $K$?}
\end{enumerate}

### (b)
\begin{enumerate}
\item[] \textit{Given this choice of $L$, what are profits as a function of $P$, $Y$, $W$, and $K$?}
\end{enumerate}

### (c)
\begin{enumerate}
\item[] \textit{Find the first-order condition for the profit-maximizing choice of $K$. Is the second-order condition satisfied?}
\end{enumerate}

### (d)
\begin{enumerate}
\item[] \textit{Solve the first-order condition in part (c) for $K$ as a function of $P$ , $Y$, $W$, and $r_{K}$. How, if at all, do changes in each of these variables affect $K$?}
\end{enumerate}



## Ejercicio 9.4, Romer (5ta Edicion)

\begin{enumerate}
\item[] \textbf{9.4}Building intuition concerning the transversality condition. Consider an individual choosing the path of $G$ to maximize $\int_{t=0}^{\infty}e^{-\rho t}\left[- \frac{a}{2}G(t)^{2} \right]dt,a>0,\rho>0$. Here $G(t)$ is the amount of garbage the individual creates at time t; for simplicity, we allow for the possibility that $G$ can be negative. The individual’s creation of garbage affects his or her stock of trash. In particular, the stock of trash, $T$, evolves according to $T=0,\dot{T}(t)=G(t)$
\end{enumerate}

### (a)
\begin{enumerate}
\item[] \textit{Prove using as little math as possible that the utility-maximizing path is $G(t) = 0 \quad \forall t$.}
\end{enumerate}

### (b)
\begin{enumerate}
\item[] \textit{Suppose we want to analyze this problem using the calculus of variations. Let $G$ be the control variable and $T$ the state variable, and let $\mu$ denote the costate variable. What is the current-value Hamiltonian?}
\end{enumerate}

### (c)
\begin{enumerate}
\item[] \textit{Find the conditions for optimality other than the transversality condition. Describe the paths of $G$ that satisfy those conditions.}
\end{enumerate}

### (d)
\begin{enumerate}
\item[] \textit{What is the transversality condition? Show that it rules out all but one of the paths you found in part (c), and that the one remaining path is the one that you showed in part (a) to be optimal: $G(t) = 0 \quad \forall t$.}
\end{enumerate}

### (e)
\begin{enumerate}
\item[] \textit{Explain in a sentence or two why the solutions in (c) other than $G(t) = 0 \quad \forall t$ look as if they are utility-maximizing if one does not consider the transversality condition, and why the transversality condition rules them out.}
\end{enumerate}



## Ejercicio 9.8, Romer (5ta Edicion)

\begin{enumerate}
\item[] \textbf{9.8}Consider the model of investment in Sections 9.2 9.5. Suppose it becomes known at some date that there will be a one-time capital levy. Specifically, capital holders will be taxed an amount equal to fraction $f$ of the value of their capital holdings at some time in the future, time $T$. Assume the economy is initially in long-run equilibrium. What happens at the time of this news? How do $K$ and $q$ behave between the time of the news and the time the levy is imposed? What happens to $K$ and $q$ at the time of the levy? How do they behave thereafter? (Hint: Is $q$ anticipated to change discontinuously at the time of the levy?)
\end{enumerate}



## Ejercicio 9.11, Romer (5ta Edicion)

\begin{enumerate}
\item[] \textbf{9.11} Suppose that $\pi(K)=a-bK$ and $C(I)=\alpha I^{2}/2$
\end{enumerate}

### (a)
\begin{enumerate}
\item[] \textit{What is the $\dot{q} = 0$ locus? What is the long-run equilibrium value of $K$?}
\end{enumerate}

### (b)
\begin{enumerate}
\item[] \textit{What is the slope of the saddle path? (Hint: Use the approach in Section 2.6.)}
\end{enumerate}




# Ejercicios prácticos

## Ejercicio 2.-
**Estudie los determinantes de la inversión agregada en México siguiendo estos pasos:**

### (a)
**Obtenga, del Inegi, datos DESESTACIONALIZADOS para México del consumo "C", datos de "I", la inversión privada (inversión fija bruta), y de "Y", el PIB, entre 1980 y 2021/IV, A FRECUENCIA TRIMESTRAL, EN TÉRMINOS REALES y grafique las tres series. (Si encuentra varias series pero ninguna cubre el periodo completo, tome una decisión ejecutiva para "unir" las series.)**

### (b)
**Grafique la relación entre los cambios de I y los de Y, es decir, grafique los puntos ($\% \Delta Y_{t}$,$\% \Delta I_{t}$) poniendo la inversión en el eje de las ordenadas.**

### (c)
**Calcule la volatilidad de cada serie y la covarianza entre las tres series de tasas de crecimiento ($\% \Delta {I}$, $\% \Delta C$ y $\% \Delta Y$),  describa cuál es más volátil y cuales cambios, si los de I o los de C están más relacionados con los de Y.**

### (d)
**Obtenga, del Banco de México, datos sobre las tasas de interés reales ($r^{r}$) de la economía $r^{r}=r^{n}-\pi$, es decir, la tasa de interés nominal, menos la tasa de inflación esperada (en cuyo caso se trata de la tasa de interés real "ex-ante"), o menos la tasa de inflación observada (en cuyo caso se trata de la "ex-post") y grafíquelas.**

### (e)
**Estime una serie de modelos lineales con el objetivo de averiguar qué variables predicen la tasa de crecimiento de la inversión $\Delta$\%$I_t$. Utilice valores corrientes y rezagados del crecimiento en el producto, de la tasa de interés real, valores rezagados de la propia tasa de cambio en la inversión y combinaciones de estas variables.**

### (f)
**Estime otra serie de modelos lineales con el objetivo de averiguar qué variables predicen la tasa de crecimiento de la inversión $\Delta$\%$I_t$: a las especificaciones del inciso anterior, agregue valores corrientes y/o rezagados de {\it la confianza empresarial} del Inegi y de {\it la confianza del consumidor} elaborado por el Inegi y el Banco de México.**

### (g)
**Interprete los resultados.** 


## Ejercicio 3.-
**Estudie la habilidad de modelo de la $q$ de Tobin para explicar las tasas de inversión de empresas individuales, siguiendo estos pasos:**

### (a)
**Con el propósito de desarrollar intuición sobre la existencia y fuente de los datos corporativos, vaya al sitio de internet de algún corporativo mexicano y obtenga su reporte anual. De ahí, obtenga el valor de los activos menos los pasivos (excepto el capital) y con ello construya el ``valor en libros'' de la empresa. Posteriormente, de dicho reporte, o del sitio de la BMV o de la BIVA, obtenga el ``valor de capitalización'' de mercado de la misma empresa y finalmente construya la variable ``Q'' como la razón de dichos valores. **

### (b)
**Construya una medida (no necesariamente una buena) de ``q'' de la empresa utilizando DOS reportes corporativos, idealmente el de un trimestre y el el mismo trimestre del año anterior, y comparando el cambio del valor en libros vs el cambio del valor de capitalización.**

### (c)
**Utilice su cuenta de GitHub.com para entrar al repositorio fisionmail, Colmex\_Macro\_2\_2022 y bajar el archivo de datos que está ahí, está en formato de stata,  ``.dta''. Cree una medida de la tasa de inversión y una medida de q de Tobin: la medida de la tasa de inversión puede ser el gasto en capital (capx) sobre el capital (ppen), o la tasa de cambio en el capital (\%$\Delta$ ppen), o la tasa de cambio de los activos (\%$\Delta$ta). **

### (d)
**Cree una medida de la ``Q'': el  valor de mercado de la empresa sobre el valor en libros de la empresa, en donde el valor de mercado es es número de acciones por el precio de la acción.**

### (e)
**Estime los coeficientes de una relación lineal entre la tasa de inversión en un periodo y la ``Q' en el mismo y también de una relación utilizando la ``Q'' del periodo inmediato anterior. **

### (f)
**Produzca un estimado del coeficiente del costo de ajuste a partir de las regresiones anteriores.** 

### (g)
**Explique, suponiendo que la función de costo de ajuste es cuadrática (es decir $C_t=b(I_t/K_t)^2K_t $), qué implican los resultados de sus regresiones sobre el costo de ajuste relativo al capital total para una inversión de 50\% del capital total y qué implican los resultados para el tiempo que le tomaría a una empresa recorrer la mitad mitad del camino entre el capital que tiene, $K$, y el que quisiera tener $K^*$.**

### (h)
**Simule una relación lineal $Y=a+bX+\epsilon$ y cree tres variables con error de medición $\tilde{X}=X+\epsilon^x$, $\tilde{\tilde{X}}=X-c  \cdot {\epsilon}$ y  $\tilde{Y}=Y+\epsilon^y$. (Es decir, primero invéntese una variable, X, genere una variable $\epsilon$ aleatoria y con esas dos genere una variable Y. Luego genere dos nuevas X's, una afectada aleatoriamente por otro error diferente, $\epsilon^x$, y otra afectada, de manera NEGATIVA, por el mismo error que incluy'o en la simulación de la Y original, y tercero, genere una nueva Y que esté afectada por una tercera variable aleatoria $\epsilon^Y$.  Finalmente, estime varias relaciones lineales:  la de la $Y$ original, con la $X$ original, la de $Y$ original, pero contra $\tilde{X}$ y $\tilde{\tilde{X}}$ y la de $\tilde{Y}$ con la $X$ original, explicando como cambia el coeficiente $\hat{b}$ en cada caso, y relacionándo sus hayazgos con el coeficiente $b$ del inciso anterior.**

### (i)
**Estime los coeficientes de una relación lineal entre la tasa de inversión en un periodo, la $q$ de Tobin en el mismo o en el periodo inmediato anterior, y el flujo de efectivo o las ganancias netas. Interprete los resultados contrastándolos con los resultados que obtuvo anteriormente.**


## Ejercicio 4.-
**Proponga una mejora al archivo Diccionario de Economía utilizando github.**

